# .prettierrc or .prettierrc.yaml
trailingComma: "es5"
tabWidth: 4
semi: true
singleQuote: true
arrowParens: always
bracketSpacing: true
cursorOffset: -1
embeddedLanguageFormatting: auto
endOfLine: lf
htmlWhitespaceSensitivity: css
insertPragma: false
jsxBracketSameLine: false
jsxSingleQuote: false
printWidth: 80
proseWrap: preserve
quoteProps: as-needed
useTabs: true
requirePragma: false
rangeStart: 0
